version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: conductor:server
    container_name: conductor-server
    build:
      context: ../
      dockerfile: docker/server/FSDockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080
    image: conductor:ui
    container_name: conductor-ui
    build:
      context: ../
      dockerfile: docker/ui/FSDockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    stdin_open: true

networks:
  internal:
